sudo: required

services:
  - docker

before_install:
- docker build -t circleci/elasticsearch .

script:
- docker run -d -p 9200:9200 circleci/elasticsearch; sleep 10
- curl --retry 10 --retry-delay 5 -v http://localhost:9200